export const BEER_STYLES = [
  "IPA",
  "Double IPA",
  "Triple IPA",
  "Session IPA",
  "NEIPA / Hazy IPA",
  "West Coast IPA",
  "Black IPA",
  "White IPA",
  "Milkshake IPA",
  "Brut IPA",
  "Rye IPA",
  "Cold IPA",
  "Mountain IPA",
  "Pale Ale",
  "American Pale Ale",
  "Amber Ale",
  "Red Ale",
  "Blonde Ale",
  "Strong Ale",
  "Lager",
  "Pilsner",
  "Helles",
  "Dunkel",
  "Schwarzbier",
  "Kellerbier",
  "Export",
  "Stout",
  "Imperial Stout",
  "Milk Stout",
  "Oatmeal Stout",
  "Pastry Stout",
  "Coffee Stout",
  "Irish Dry Stout",
  "Porter",
  "Imperial Porter",
  "Baltic Porter",
  "Pastry Porter",
  "Saison",
  "Farmhouse Ale",
  "Witbier",
  "Hefeweizen",
  "Kristalweizen",
  "Weizenbock",
  "Dunkelweizen",
  "Berliner Weisse",
  "Gose",
  "Sour Ale",
  "Fruited Sour",
  "Pastry Sour",
  "Smoothie Sour",
  "Wild Ale",
  "Lambic",
  "Gueuze",
  "Kriek",
  "Flanders Red Ale",
  "Oud Bruin",
  "Triple (Belge)",
  "Double / Dubbel",
  "Quadrupel",
  "Enkel / Patersbier",
  "Belgian Golden Strong Ale",
  "Belgian Dark Strong Ale",
  "Bock",
  "Doppelbock",
  "Eisbock",
  "Maibock",
  "Altbier",
  "Kölsch",
  "Barleywine",
  "Old Ale",
  "Scotch Ale / Wee Heavy",
  "Irish Red Ale",
  "English Bitter",
  "ESB",
  "Mild Ale",
  "Smoked Beer / Rauchbier",
  "Wood-Aged Beer",
  "Barrel-Aged",
  "Triple",
  "Vière",
  "Vière (Hybride Bière/Vin)",
  "Hard Seltzer",
  "Non-Alcoholic",
  "Pastry Ale",
] as const;

export const SORTED_BEER_STYLES = [...BEER_STYLES].sort((a, b) =>
  a.localeCompare(b, "fr"),
);
